[package]
name = "beefy-primitives"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
codec = { version = "2.0.0", package = "parity-scale-codec", default-features = false, features = ["derive"] }
scale-info = { version = "1.0", default-features = false, features = ["derive"], optional = true }

sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "grandpa_finality_logs" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "grandpa_finality_logs" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "grandpa_finality_logs" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "grandpa_finality_logs" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "grandpa_finality_logs" }

[dev-dependencies]
hex-literal = "0.3"

sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "grandpa_finality_logs" }

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-api/std",
	"sp-application-crypto/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
